
spring.datasource.url = jdbc:mysql://34.176.97.175:3306/DouceAmitie
spring.datasource.username = root
spring.datasource.password = 21dejunio

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
